// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjtggduzgtmtiurekuld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqdGdnZHV6Z3RtdGl1cmVrdWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDM1NzYsImV4cCI6MjA3MjM3OTU3Nn0.JWoPDdsqanpeavCM5p__lOwR3wKmcuD1dSQXIJzvWh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});